import time
print ('')
print ('Calculator')
time.sleep(69)
print ('  ✓ calculator functionality should have working number buttons')
time.sleep(100)
print ('  ✓ calculator functionality should have working add button')
time.sleep(60)
print ('  ✓ calculator functionality should have working subtract button')
time.sleep(30)
print ('  ✓ calculator functionality should have working divide button ')
time.sleep(48)
print ('  ✓ calculator functionality should have working multiply button')
time.sleep(25)
print ('  ✓ calculator functionality should be able to chain multiple operators')
time.sleep(27)
print ('  ✓ calculator functionality should work for negative numbers')
time.sleep(20)
print ('  ✓ calculator functionality should work for decimals')
time.sleep(23)
print ('  ✓ calculator functionality should work for very large numbers')
time.sleep(20)
print ('  ✓ calculator functionality should have working divide button not infinity with')
time.sleep(27)
print ('  ✓ calculator functionality should have working divide button not infinity with zero')
time.sleep(21)
print ('')
print ('10 passing (384s)')

